// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1yvTe8OoIYv1n7gdpRYg1wdOz4wBVonY',
    appId: '1:769197054026:web:dcbc86e21c93d11b70aeb3',
    messagingSenderId: '769197054026',
    projectId: 'swaranusa-quiz',
    authDomain: 'swaranusa-quiz.firebaseapp.com',
    storageBucket: 'swaranusa-quiz.firebasestorage.app',
    measurementId: 'G-46P8JEMXJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAqoV757ViGziffzqvVzkiaNdKcdzAbI',
    appId: '1:769197054026:android:8e69246f7a802c1e70aeb3',
    messagingSenderId: '769197054026',
    projectId: 'swaranusa-quiz',
    storageBucket: 'swaranusa-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAzFs2D5bWYWIdyLYSa5i9tal-xEoBAIE',
    appId: '1:769197054026:ios:772cbca305736be070aeb3',
    messagingSenderId: '769197054026',
    projectId: 'swaranusa-quiz',
    storageBucket: 'swaranusa-quiz.firebasestorage.app',
    iosClientId: '769197054026-eqhb6b17ocel56ev35mttd6l1d49qqd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.swaranusaquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAzFs2D5bWYWIdyLYSa5i9tal-xEoBAIE',
    appId: '1:769197054026:ios:772cbca305736be070aeb3',
    messagingSenderId: '769197054026',
    projectId: 'swaranusa-quiz',
    storageBucket: 'swaranusa-quiz.firebasestorage.app',
    iosClientId: '769197054026-eqhb6b17ocel56ev35mttd6l1d49qqd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.swaranusaquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1yvTe8OoIYv1n7gdpRYg1wdOz4wBVonY',
    appId: '1:769197054026:web:07d41c3c00e3dd9170aeb3',
    messagingSenderId: '769197054026',
    projectId: 'swaranusa-quiz',
    authDomain: 'swaranusa-quiz.firebaseapp.com',
    storageBucket: 'swaranusa-quiz.firebasestorage.app',
    measurementId: 'G-X9Z78X3BFW',
  );
}
